---
- name: Delete Metrics Server
  hosts: master
  tasks:
  - name: delete metrics server manifest
    ansible.builtin.command:
      cmd: kubectl delete --ignore-not-found=true -f /tmp/metrics-server-components.yaml

