---
- name: Create admin user
  hosts: masters[0]
  tasks:
  - name: copy admin service account manifest
    ansible.builtin.template:
      src: ansible.tp.admin-service-account.yaml
      dest: admin-service-account.yaml
  
  - name: apply admin service account manifest
    ansible.builtin.command:
      kubectl apply -f admin-service-account.yaml

  - name: copy cluster role binding manifest
    ansible.builtin.template:
      src: ansible.tp.admin-rbac.yaml
      dest: admin-rbac.yaml

  - name: apply cluster role binding manifest
    ansible.builtin.command:
      kubectl apply -f admin-rbac.yaml

  - name: get admin account secret name
    ansible.builtin.shell: |
      kubectl -n kube-system get secret | grep "^kubernetes-admin-" | cut -d' ' -f1
    register: admin_secret_name

  - name: get admin secret description
    ansible.builtin.command:
      cmd: kubectl --namespace kube-system describe secret {{ admin_secret_name.stdout }}
    register: admin_secret_describe  

  - name: print admin secret (use token to login dashboard)
    ansible.builtin.debug:
      msg: "{{ admin_secret_describe.stdout }}"

  