---
- name: Create admin user
  hosts: master
  tasks:
  - name: copy admin service account manifest
    ansible.builtin.template:
      src: ansible.tp.admin-service-account.yaml
      dest: /tmp/admin-service-account.yaml
  
  - name: apply admin service account manifest
    ansible.builtin.command:
      kubectl apply -f /tmp/admin-service-account.yaml

  - name: copy cluster role binding manifest
    ansible.builtin.template:
      src: ansible.tp.admin-rbac.yaml
      dest: /tmp/admin-rbac.yaml

  - name: apply cluster role binding manifest
    ansible.builtin.command:
      kubectl apply -f /tmp/admin-rbac.yaml
