---
# this playbook install nfs server on master, nfs client on workers
- name: Setup NFS share storage
  hosts: all
  become: true
  gather_facts: true
  any_errors_fatal: true
  gather_subset: 
    - all
  roles:
    - k8s-nfs-storage