---
- name: Delete Metrics Server
  hosts: masters[0]
  tasks:
  - name: delete metrics server manifest
    ansible.builtin.command:
      cmd: kubectl delete --ignore-not-found=true -f metrics-server-components.yaml

