---
- name: Get apt update and upgrade on all nodes
  hosts: all
  become: true
  tasks:
  - name: apt update and safe upgrade
    ansible.builtin.apt:
      update_cache: yes
      upgrade: safe

#- name: reboot
#  ansible.builtin.reboot:
#    post_reboot_delay: 30
#    reboot_timeout: 120
