---
- name: Get token from single master node
  hosts: masters[0]
  tasks:
  - name: get join command
    ansible.builtin.command:
      cmd: kubeadm token create --print-join-command
    register: join_worker_node_command

  - name: print the join command
    ansible.builtin.debug:
      msg: "{{ join_worker_node_command.stdout }}"

  # another way to store the command to a variable manually
  - name: add join command to hostsvars
    ansible.builtin.add_host:
      name: JOIN_WORKER_NODE_COMMAND
      cmd: "{{ join_worker_node_command.stdout }}"

- name: Add worker nodes
  hosts: workers
  become: true
  tasks:
  - name: add endpoint record in /etc/hosts
    ansible.builtin.lineinfile:
      path: /etc/hosts
      line: "{{ hostvars['master'].ansible_host }} {{ CLUSTER_API_DOMAIN_NAME }}"
      state: present

  - name: add worker node
    ansible.builtin.command:
      cmd: "{{ hostvars['master']['join_worker_node_command'].stdout }}"
    register: join_worker_output

#  - name: add worker node
#    ansible.builtin.command:
#      cmd: "{{ hostvars['JOIN_WORKER_NODE_COMMAND']['cmd'] }}"
#    register: join_worker_output

  - name: print join worker output
    ansible.builtin.debug:
      msg: "{{ join_worker_output.stdout }}"

- name: Check worker nodes
  hosts: masters[0]
  tasks:
  - name: get nodes status
    ansible.builtin.command:
      cmd: kubectl get nodes -o wide
    register: get_nodes_status
  
  - name: print node status
    ansible.builtin.debug:
      msg: "{{ get_nodes_status.stdout }}"