---
- name: update apt cache
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600
  ignore_errors: yes

- name: install nfs server
  ansible.builtin.apt:
    state: present
    pkg:
    - nfs-kernel-server

- name: create nfs share folder
  ansible.builtin.file:
    path: "{{ NFS_SHARE_DIR }}/{{ item }}"
    state: directory
    mode: "{{ NFS_SHARE_DIR_PERMISSION }}"
    owner: "{{ NFS_SHARE_DIR_OWNER }}"
    group: "{{ NFS_SHARE_DIR_GROUP }}"
  loop: "{{ NFS_SHARE_SUB_DIR }}"

- name: create nfs export file
  ansible.builtin.lineinfile:
    path: /etc/exports
    regexp: "^{{ NFS_SHARE_DIR }}/{{ item }} "
    line: "{{ NFS_SHARE_DIR }}/{{ item }} {{ hostvars[inventory_hostname]['ansible_default_ipv4']['network'] }}/24(rw,sync,no_root_squash,no_subtree_check)"
    firstmatch: yes
  loop: "{{ NFS_SHARE_SUB_DIR }}"

- name: export nfs
  ansible.builtin.command:
    cmd: exportfs -a

- name: restart nfs server
  ansible.builtin.service:
    name: nfs-kernel-server
    state: restarted

- name: check rpcinfo
  ansible.builtin.command:
    cmd: "rpcinfo -p {{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
  register: nfs_rpcinfo

- name: print rpcinfo
  ansible.builtin.debug:
    msg: "{{ nfs_rpcinfo.stdout }}"